### ISSUE TITLE
Problem with SelectChannel() methods.

### ISSUE THREAD

**Issue by jcracine** [closedcube/ClosedCube_TCA9548A_Arduino#2]
Inside the selectChannel() methods, there is no need to add 1 to channels when writing inside the register. In fact, this causes problem where all channels are offset by one. Here is the corrected version of the methods:

`
uint8_t ClosedCube::Wired::TCA9548A::selectChannel(uint8_t channel)
 {
	uint8_t result = 0xff;
	if (channel >= 0 && channel < TCA9548A_MAX_CHANNELS)
        {
		Wire.beginTransmission(_address);
		Wire.write( 1 << channel);
		
		_currentChannel = channel;
		result = Wire.endTransmission();
	} 
	return result;
}
`

**Comment by puenka** [comment]
I have the exact same issue with this library and can confirm this behaviour.
